### ISSUE TITLE
Cannot set property 'openerId' of undefined

### ISSUE THREAD

**Issue by MaximeFrancoeur** [auth0-samples/auth0-electron-samples#4]
I cannot test this project with my personal clientId and domain.

After execute `npm install` and `npm start` I click on login with Facebook or Google or any else and I receive a popup with this error `Cannot set property 'openerId' of undefined`

```
Full stacktrace : 
Uncaught Exception:
TypeError: Cannot set property 'openerId' of undefined
    at mergeBrowserWindowOptions (/Users/MaximeFr/Desktop/auth0-electron-samples-sample/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/guest-window-manager.js:44:35)
    at EventEmitter.<anonymous> (/Users/MaximeFr/Desktop/auth0-electron-samples-sample/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/guest-window-manager.js:144:13)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Users/MaximeFr/Desktop/auth0-electron-samples-sample/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

**Comment by MaximeFrancoeur** [comment]
Any update ?

**Comment by wmeitzler** [comment]
This looks to be an issue with Electron handling opening a new browser window
https://github.com/electron/electron/issues/7519

**Comment by MaximeFrancoeur** [comment]
I test with Electron 1.4.3 and I have same exception.

**Comment by MaximeFrancoeur** [comment]
Thank you your solution work fine.
